services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: WebApiMessenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/gpadmin
      - ./PgAdmin/SetupServer.json:/pgadmin4/servers.json

  webapiserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5175:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Username=postgres;Password=1;Database=WebApiMessenger
    depends_on:
      - postgres

  client1:
    build:
      context: .
      dockerfile: WebApiClient1/Dockerfile
    depends_on:
      - webapiserver
      - postgres
    ports:
      - "5171:80"

  client2:
    build:
      context: .
      dockerfile: WebApiClient2/Dockerfile
    depends_on:
      - webapiserver
      - postgres
    ports:
      - "5172:80"

  client3:
    build:
      context: .
      dockerfile: WebApiClient3/Dockerfile
    depends_on:
      - webapiserver
      - postgres
    ports:
      - "5173:80"

volumes:
  postgres-data:  
  pgadmin-data: